// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1647253230);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1647253215);
user_pref("browser.search.region", "IN");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1647253222963");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220106182030");
user_pref("extensions.lastAppVersion", "91.5.0");
user_pref("extensions.lastPlatformVersion", "91.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"983be991-0850-4725-ba32-d4cc507b00bb\",\"google@search.mozilla.org\":\"f1486285-546a-49e4-ba1a-0f518ceaa411\",\"ddg@search.mozilla.org\":\"e279e6b7-7463-401d-953f-8b9e9d18b909\",\"amazondotcom@search.mozilla.org\":\"5c1bc870-7f29-43e0-81f0-bfa345da229f\",\"wikipedia@search.mozilla.org\":\"b1d0fd0c-f9a5-4864-a8c6-461dcb5e5842\",\"bing@search.mozilla.org\":\"ab7debbe-a941-45e0-b06b-63159d297db4\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 30);
user_pref("mailnews.database.global.datastore.id", "eee7eb68-9ac2-40cd-8c78-4376856cdb6");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.5.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "99c26353-21e1-4d30-b474-d2b34a90f93f");
user_pref("toolkit.telemetry.previousBuildID", "20220106182030");
